// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nakgfwkpxunpgktjuvfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ha2dmd2tweHVucGdrdGp1dmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mjc5OTgsImV4cCI6MjA2NzAwMzk5OH0.-5_ViKvtoaCeDBaUkAygqbG5EIfPGVf8uVnfq3lCgWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});